cmake_minimum_required(VERSION 3.25)
# Configure-only regression: inspect the actual imported artifact selected by
# generators, without needing to link fake libraries or a compiler installation.
# Start clean, so library paths cached by a previous run cannot hide a change to the search.
file(REMOVE_RECURSE "${TEST_BINARY_DIR}")
set(prefix "${TEST_BINARY_DIR}/prefix")
file(MAKE_DIRECTORY "${prefix}/include" "${prefix}/lib" "${prefix}/debug/lib")
file(WRITE "${prefix}/include/wepoll.h" "")
file(WRITE "${prefix}/lib/wepoll.lib" "")
file(WRITE "${prefix}/debug/lib/wepoll.lib" "")
include(CMakePackageConfigHelpers)
configure_package_config_file("${TEST_SOURCE_DIR}/cmake/slick-socketConfig.cmake.in"
    "${prefix}/lib/cmake/slick-socket/slick-socketConfig.cmake"
    INSTALL_DESTINATION lib/cmake/slick-socket)
file(COPY "${TEST_SOURCE_DIR}/cmake/FindWepoll.cmake" DESTINATION "${prefix}/lib/cmake/slick-socket")
file(WRITE "${prefix}/lib/cmake/slick-socket/slick-socketTargets.cmake"
    "add_library(slick::socket INTERFACE IMPORTED)\n")
file(WRITE "${TEST_BINARY_DIR}/consumer/CMakeLists.txt" [=[
cmake_minimum_required(VERSION 3.25)
project(wepoll_selection NONE)
find_package(slick-socket CONFIG REQUIRED)
file(GENERATE OUTPUT "${CMAKE_BINARY_DIR}/selected-$<CONFIG>.txt"
    CONTENT "$<TARGET_FILE:wepoll::wepoll>")
]=])
# vcpkg-order: the vcpkg toolchain searches debug/ before the Release prefix for multi-config builds.
# legacy-cache: an older build tree has the Debug library cached in WEPOLL_LIBRARY by find_library.
file(WRITE "${TEST_BINARY_DIR}/legacy-cache.cmake"
    "set(WEPOLL_LIBRARY \"${prefix}/debug/lib/wepoll.lib\" CACHE FILEPATH \"Path to a library.\")\n")
foreach(case multi vcpkg-order legacy-cache single-debug single-release release-only debug-only override)
    if(case STREQUAL "release-only")
        file(REMOVE "${prefix}/debug/lib/wepoll.lib")
    elseif(case STREQUAL "debug-only")
        file(REMOVE "${prefix}/lib/wepoll.lib")
        file(WRITE "${prefix}/debug/lib/wepoll.lib" "")
    endif()
    set(prefix_path "${prefix}")
    if(case STREQUAL "vcpkg-order")
        set(prefix_path "${prefix}/debug" "${prefix}")
    endif()
    set(options)
    if(case STREQUAL "legacy-cache")
        list(APPEND options -C "${TEST_BINARY_DIR}/legacy-cache.cmake")
    endif()
    if(TEST_NINJA)
        list(APPEND options "-DCMAKE_MAKE_PROGRAM=${TEST_NINJA}")
    endif()
    if(case MATCHES "^single-")
        set(generator Ninja)
        if(case STREQUAL "single-debug")
            set(configs Debug)
        else()
            set(configs Release)
        endif()
        list(APPEND options "-DCMAKE_BUILD_TYPE=${configs}")
    else()
        set(generator "Ninja Multi-Config")
        set(configs Debug Release RelWithDebInfo)
    endif()
    if(case STREQUAL "override")
        list(APPEND options "-DWEPOLL_LIBRARY=${prefix}/custom.lib")
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}" -S "${TEST_BINARY_DIR}/consumer"
        -B "${TEST_BINARY_DIR}/${case}" -G "${generator}"
        "-DCMAKE_PREFIX_PATH=${prefix_path}" ${options}
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(result)
        message(FATAL_ERROR "${case}: ${output}\n${error}")
    endif()
    foreach(config IN LISTS configs)
        file(READ "${TEST_BINARY_DIR}/${case}/selected-${config}.txt" selected)
        if(case STREQUAL "override")
            set(expected "${prefix}/custom.lib")
        elseif(case STREQUAL "debug-only" OR (config STREQUAL "Debug" AND NOT case STREQUAL "release-only"))
            set(expected "${prefix}/debug/lib/wepoll.lib")
        else()
            set(expected "${prefix}/lib/wepoll.lib")
        endif()
        cmake_path(NORMAL_PATH expected)
        if(NOT selected STREQUAL expected)
            message(FATAL_ERROR "${case}/${config}: selected '${selected}', expected '${expected}'")
        endif()
    endforeach()
endforeach()
